[package]
name = "sqry-lang-html"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "HTML language plugin for sqry"

[dependencies]
sqry-core = { version = "23.0.2", path = "../sqry-core" }
anyhow.workspace = true
log.workspace = true
tree-sitter.workspace = true
tree-sitter-html.workspace = true
streaming-iterator.workspace = true

[dev-dependencies]
sqry-core = { path = "../sqry-core", features = ["test-support"] }
