//! Macro-generated symbol diffing (4.5f diffing).
//!
//! Compares original and expanded source code to identify symbols that were
//! generated by macro expansion. Uses fully-qualified symbol names (not just
//! simple names) to avoid collisions across modules and impl blocks.
//!
//! # Diffing Strategy
//!
//! 1. Parse both original and expanded source with tree-sitter
//! 2. Extract qualified symbol names from both
//! 3. New symbols = expanded set minus original set
//! 4. Modified symbols = same qualified name but different spans/signatures
//!
//! # Non-deterministic Macros
//!
//! If `cargo expand` produces different output on consecutive runs (checked via
//! SHA-256 of expanded output), the cache entry is marked
//! `confidence: "non_deterministic"` and generated symbols are excluded from
//! the graph.

use std::collections::{HashMap, HashSet};

use super::expand_cache::{GeneratedSymbolKind, ScopeSegment};

/// Result of comparing original and expanded symbol sets.
#[derive(Debug, Clone)]
pub struct DiffResult {
    /// Symbols present in expanded but not original — macro-generated.
    pub generated: Vec<String>,
    /// Symbols present in both but with different signatures — possibly modified
    /// by macro expansion.
    pub possibly_modified: Vec<String>,
    /// Symbols present in original but not expanded — removed (rare, usually
    /// indicates a `cfg` gate or conditional compilation difference).
    pub removed: Vec<String>,
}

impl DiffResult {
    /// Returns true if no differences were found.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.generated.is_empty() && self.possibly_modified.is_empty() && self.removed.is_empty()
    }

    /// Total number of differences.
    #[must_use]
    pub fn total_changes(&self) -> usize {
        self.generated.len() + self.possibly_modified.len() + self.removed.len()
    }
}

/// Information about a symbol extracted from source code.
#[derive(Debug, Clone)]
pub struct SymbolInfo {
    /// Fully-qualified name (e.g., `my_crate::MyStruct`, `my_crate::<MyStruct as Debug>::fmt`).
    ///
    /// Carries the crate prefix and the `<Type as Trait>` decoration; used ONLY
    /// as the [`diff_symbols`] key. The Phase 1b index consumer reconstructs the
    /// graph-convention name from the structured pieces below instead.
    pub qualified_name: String,
    /// Simple name (e.g., `MyStruct`, `fmt`).
    pub simple_name: String,
    /// Optional signature string for detecting modifications.
    pub signature: Option<String>,
    /// Start line in source (1-indexed).
    pub start_line: u32,
    /// End line in source (1-indexed).
    pub end_line: u32,
    /// The FULL ordered scope chain from the crate root to (but not including)
    /// this symbol, matching exactly the segments the live `scope_node_name`
    /// pushes (`mod` = module, `struct` / `enum` / `trait` / `type` = type). Does
    /// NOT include a crate segment, the `impl` type, or the symbol itself.
    pub scope_segments: Vec<ScopeSegment>,
    /// For methods (items inside an `impl` block): the plain, trimmed impl `type`
    /// field text (e.g. `"MyStruct"`), matching the live `current_impl_type`.
    /// `None` for free items.
    pub impl_type: Option<String>,
    /// Declaration kind recovered from the tree-sitter node kind (plus impl
    /// context, so a `fn` inside an `impl` is [`GeneratedSymbolKind::Method`]).
    pub kind: GeneratedSymbolKind,
}

/// Diff two sets of symbols to find generated, modified, and removed entries.
///
/// Uses fully-qualified names as the key for comparison. Symbols with the
/// same qualified name but different signatures are classified as
/// `possibly_modified`.
///
/// # Arguments
///
/// * `original_symbols` — symbols from the unexpanded source
/// * `expanded_symbols` — symbols from the expanded source
#[must_use]
pub fn diff_symbols(
    original_symbols: &[SymbolInfo],
    expanded_symbols: &[SymbolInfo],
) -> DiffResult {
    let original_by_name: HashMap<&str, &SymbolInfo> = original_symbols
        .iter()
        .map(|s| (s.qualified_name.as_str(), s))
        .collect();

    let expanded_by_name: HashMap<&str, &SymbolInfo> = expanded_symbols
        .iter()
        .map(|s| (s.qualified_name.as_str(), s))
        .collect();

    let original_names: HashSet<&str> = original_by_name.keys().copied().collect();
    let expanded_names: HashSet<&str> = expanded_by_name.keys().copied().collect();

    // Generated = in expanded but not in original.
    let generated: Vec<String> = expanded_names
        .difference(&original_names)
        .map(|name| (*name).to_string())
        .collect();

    // Removed = in original but not in expanded.
    let removed: Vec<String> = original_names
        .difference(&expanded_names)
        .map(|name| (*name).to_string())
        .collect();

    // Possibly modified = in both but with different signatures.
    let possibly_modified: Vec<String> = original_names
        .intersection(&expanded_names)
        .filter(|name| {
            let orig = original_by_name[*name];
            let expanded = expanded_by_name[*name];
            orig.signature != expanded.signature
        })
        .map(|name| (*name).to_string())
        .collect();

    DiffResult {
        generated,
        possibly_modified,
        removed,
    }
}

/// Check if two expansion outputs are deterministic by comparing their SHA-256
/// hashes.
///
/// If the hashes differ, the macro expansion is non-deterministic and should
/// be marked with `confidence: "non_deterministic"`.
///
/// # Arguments
///
/// * `hash_a` — SHA-256 hex digest of the first expansion output
/// * `hash_b` — SHA-256 hex digest of the second expansion output
#[must_use]
pub fn is_deterministic(hash_a: &str, hash_b: &str) -> bool {
    hash_a == hash_b
}

/// Parse Rust source text with the tree-sitter grammar and extract its
/// qualified symbols (including the Phase 1b structured `scope_segments` /
/// `impl_type` / `kind` pieces).
///
/// Convenience wrapper over [`extract_symbols_from_tree`] for callers (such as
/// the `sqry cache expand` writer) that have raw source text rather than an
/// already-parsed tree, and that do not otherwise depend on tree-sitter.
/// Returns an empty vector if the grammar cannot be loaded or the source fails
/// to parse.
#[must_use]
pub fn extract_symbols_from_source(source: &str, crate_name: &str) -> Vec<SymbolInfo> {
    extract_symbols_from_source_in_module(source, crate_name, None)
}

/// Same as [`extract_symbols_from_source`], but seeds the extraction with a
/// file-level module path so a file that is NOT the crate root (e.g. `src/foo.rs`
/// -> module `foo`, `src/foo/bar.rs` -> module `foo::bar`) yields symbols in the
/// SAME crate-relative namespace that `cargo expand` produces.
///
/// `cargo expand` inlines every file-backed module into `mod <name> { .. }`, so
/// an item `bar` in `src/foo.rs` appears in the expanded output as
/// `crate::foo::bar` with a leading `foo` module scope segment. Extracting the
/// original file WITHOUT this prefix would yield `crate::bar` (no `foo`), so
/// [`diff_symbols`] would see `crate::foo::bar` as "generated" and wrongly flag
/// the ordinary file-backed-module item as macro-generated. Seeding the file
/// module path puts both sides of the diff in the same namespace.
///
/// `file_module_path` follows the `ModuleResolver::compute_file_module_path`
/// convention: `None` for crate roots (`lib.rs` / `main.rs`), `Some("foo")` for
/// `src/foo.rs`, `Some("foo::bar")` for `src/foo/bar.rs` or `src/foo/bar/mod.rs`.
#[must_use]
pub fn extract_symbols_from_source_in_module(
    source: &str,
    crate_name: &str,
    file_module_path: Option<&str>,
) -> Vec<SymbolInfo> {
    let mut parser = tree_sitter::Parser::new();
    let language: tree_sitter::Language = tree_sitter_rust::LANGUAGE.into();
    if parser.set_language(&language).is_err() {
        return Vec::new();
    }
    let Some(tree) = parser.parse(source.as_bytes(), None) else {
        return Vec::new();
    };
    extract_symbols_from_tree_in_module(&tree, source.as_bytes(), crate_name, file_module_path)
}

/// Extract symbol names from a tree-sitter parse tree.
///
/// Walks the tree and extracts qualified names for all top-level definitions:
/// functions, structs, enums, traits, impl blocks, type aliases, constants,
/// and statics.
///
/// # Arguments
///
/// * `tree`: parsed tree-sitter tree
/// * `content`: source file bytes
/// * `crate_name`: crate name prefix for qualified names
#[must_use]
pub fn extract_symbols_from_tree(
    tree: &tree_sitter::Tree,
    content: &[u8],
    crate_name: &str,
) -> Vec<SymbolInfo> {
    extract_symbols_from_tree_in_module(tree, content, crate_name, None)
}

/// Extract symbol names from a parse tree, seeding a file-level module path.
///
/// See [`extract_symbols_from_source_in_module`] for why the module prefix
/// matters. `file_module_path` seeds BOTH the crate-prefixed diff-key path
/// (`crate::foo`) AND the structured `scope_segments` accumulator (one
/// `is_module: true` segment per `::`-delimited component), so the original-file
/// symbols land in the exact namespace `cargo expand` produces.
#[must_use]
pub fn extract_symbols_from_tree_in_module(
    tree: &tree_sitter::Tree,
    content: &[u8],
    crate_name: &str,
    file_module_path: Option<&str>,
) -> Vec<SymbolInfo> {
    let mut symbols = Vec::new();
    let (scope_prefix, seed_segments): (String, Vec<ScopeSegment>) = match file_module_path {
        None | Some("") => (crate_name.to_string(), Vec::new()),
        Some(module_path) => {
            let prefix = format!("{crate_name}::{module_path}");
            let segments = module_path
                .split("::")
                .map(|name| ScopeSegment {
                    name: name.to_string(),
                    is_module: true,
                })
                .collect();
            (prefix, segments)
        }
    };
    extract_from_node(
        tree.root_node(),
        content,
        &scope_prefix,
        &seed_segments,
        None,
        &mut symbols,
    );
    symbols
}

/// Map a leaf/type tree-sitter node kind (plus impl context) to a
/// [`GeneratedSymbolKind`].
fn symbol_kind_for(node_kind: &str, impl_type: Option<&str>) -> GeneratedSymbolKind {
    match node_kind {
        "function_item" => {
            if impl_type.is_some() {
                GeneratedSymbolKind::Method
            } else {
                GeneratedSymbolKind::Function
            }
        }
        // Unions have no dedicated kind / helper sink; treat them like structs.
        "struct_item" | "union_item" => GeneratedSymbolKind::Struct,
        "enum_item" => GeneratedSymbolKind::Enum,
        "trait_item" => GeneratedSymbolKind::Trait,
        "type_item" => GeneratedSymbolKind::TypeAlias,
        "const_item" | "static_item" => GeneratedSymbolKind::Constant,
        "mod_item" => GeneratedSymbolKind::Module,
        "impl_item" => GeneratedSymbolKind::Impl,
        _ => GeneratedSymbolKind::Other,
    }
}

/// Recursively extract symbols from a tree-sitter node and its children.
///
/// `scope_prefix` is the crate-prefixed diff key path (unchanged from the
/// original behaviour). `scope_segments` is the SEPARATE structured accumulator
/// that mirrors exactly what the live `scope_node_name` pushes (module + type
/// segments, NO crate segment, NO `impl` segment); `impl_type` is the plain impl
/// `type` text threaded to the methods extracted from an impl body.
fn extract_from_node(
    node: tree_sitter::Node,
    content: &[u8],
    scope_prefix: &str,
    scope_segments: &[ScopeSegment],
    impl_type: Option<&str>,
    symbols: &mut Vec<SymbolInfo>,
) {
    let kind = node.kind();

    match kind {
        "function_item" | "struct_item" | "enum_item" | "trait_item" | "type_item"
        | "const_item" | "static_item" | "union_item" => {
            if let Some(name_node) = node.child_by_field_name("name")
                && let Ok(name) = name_node.utf8_text(content)
            {
                let qualified = format!("{scope_prefix}::{name}");
                let signature = extract_signature(node, content);
                symbols.push(SymbolInfo {
                    qualified_name: qualified.clone(),
                    simple_name: name.to_string(),
                    signature,
                    #[allow(clippy::cast_possible_truncation)] // Graph storage: node/edge index counts fit in u32
                    start_line: node.start_position().row as u32 + 1,
                    #[allow(clippy::cast_possible_truncation)] // Graph storage: node/edge index counts fit in u32
                    end_line: node.end_position().row as u32 + 1,
                    scope_segments: scope_segments.to_vec(),
                    impl_type: impl_type.map(str::to_string),
                    kind: symbol_kind_for(kind, impl_type),
                });

                let child_prefix = qualified;
                match kind {
                    // Type wrappers push a `is_module: false` scope segment (they
                    // are what `scope_node_name` pushes). A type cannot contain an
                    // `impl`, so impl context resets to `None` inside its body.
                    "struct_item" | "enum_item" | "trait_item" | "type_item" => {
                        let mut child_segments = scope_segments.to_vec();
                        child_segments.push(ScopeSegment {
                            name: name.to_string(),
                            is_module: false,
                        });
                        extract_children(
                            node,
                            content,
                            &child_prefix,
                            &child_segments,
                            None,
                            symbols,
                        );
                    }
                    // Functions / consts / statics / unions are naming leaves:
                    // `scope_node_name` pushes NO segment for them. Nested items
                    // inherit the current scope + impl context (a nested `fn`
                    // inside a method keeps the enclosing impl type, matching the
                    // live visitor).
                    _ => {
                        extract_children(
                            node,
                            content,
                            &child_prefix,
                            scope_segments,
                            impl_type,
                            symbols,
                        );
                    }
                }
                return;
            }
        }

        "impl_item" => {
            if let Some(type_node) = node.child_by_field_name("type")
                && let Ok(type_name) = type_node.utf8_text(content)
            {
                // Diff-key prefix: keep the `<Type as Trait>` decoration so the
                // qualified_name diff key stays unique per impl.
                let impl_prefix = if let Some(trait_node) = node.child_by_field_name("trait") {
                    if let Ok(trait_name) = trait_node.utf8_text(content) {
                        format!("{scope_prefix}::<{type_name} as {trait_name}>")
                    } else {
                        format!("{scope_prefix}::{type_name}")
                    }
                } else {
                    format!("{scope_prefix}::{type_name}")
                };

                // The live graph names methods with the PLAIN impl type (trait
                // dropped), so thread the trimmed `type` text as `impl_type`. The
                // `impl_item` node itself pushes NO scope segment.
                let plain_impl_type = type_name.trim();

                if let Some(body) = node.child_by_field_name("body") {
                    extract_children(
                        body,
                        content,
                        &impl_prefix,
                        scope_segments,
                        Some(plain_impl_type),
                        symbols,
                    );
                }
                return;
            }
        }

        "mod_item" => {
            if let Some(name_node) = node.child_by_field_name("name")
                && let Ok(name) = name_node.utf8_text(content)
            {
                let mod_prefix = format!("{scope_prefix}::{name}");
                let mut child_segments = scope_segments.to_vec();
                child_segments.push(ScopeSegment {
                    name: name.to_string(),
                    is_module: true,
                });
                // A module resets impl context.
                extract_children(node, content, &mod_prefix, &child_segments, None, symbols);
                return;
            }
        }

        _ => {}
    }

    // Default: recurse into children, carrying the current scope + impl context.
    extract_children(
        node,
        content,
        scope_prefix,
        scope_segments,
        impl_type,
        symbols,
    );
}

/// Extract symbols from a node's children.
fn extract_children(
    node: tree_sitter::Node,
    content: &[u8],
    scope_prefix: &str,
    scope_segments: &[ScopeSegment],
    impl_type: Option<&str>,
    symbols: &mut Vec<SymbolInfo>,
) {
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        extract_from_node(
            child,
            content,
            scope_prefix,
            scope_segments,
            impl_type,
            symbols,
        );
    }
}

/// Extract a simplified signature from a function or type definition.
fn extract_signature(node: tree_sitter::Node, content: &[u8]) -> Option<String> {
    match node.kind() {
        "function_item" => {
            // Extract parameter list and return type.
            let params = node
                .child_by_field_name("parameters")
                .and_then(|n| n.utf8_text(content).ok())
                .unwrap_or("()");
            let return_type = node
                .child_by_field_name("return_type")
                .and_then(|n| n.utf8_text(content).ok())
                .unwrap_or("");
            Some(format!("{params} {return_type}").trim().to_string())
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tree_sitter::Parser;

    fn parse_rust(source: &str) -> tree_sitter::Tree {
        let mut parser = Parser::new();
        let lang: tree_sitter::Language = tree_sitter_rust::LANGUAGE.into();
        parser.set_language(&lang).unwrap();
        parser.parse(source.as_bytes(), None).unwrap()
    }

    /// Build a diff-test `SymbolInfo`. `diff_symbols` keys only on
    /// `qualified_name`, so the structured Phase 1b fields are irrelevant here.
    fn si(
        qualified: &str,
        simple: &str,
        signature: Option<&str>,
        start: u32,
        end: u32,
    ) -> SymbolInfo {
        SymbolInfo {
            qualified_name: qualified.to_string(),
            simple_name: simple.to_string(),
            signature: signature.map(str::to_string),
            start_line: start,
            end_line: end,
            scope_segments: Vec::new(),
            impl_type: None,
            kind: GeneratedSymbolKind::Other,
        }
    }

    /// Look up an extracted symbol by its crate-prefixed qualified name.
    fn find<'a>(symbols: &'a [SymbolInfo], qualified: &str) -> &'a SymbolInfo {
        symbols
            .iter()
            .find(|s| s.qualified_name == qualified)
            .unwrap_or_else(|| panic!("symbol {qualified} not extracted"))
    }

    #[test]
    fn test_symbol_diffing() {
        let original = vec![
            si("my_crate::MyStruct", "MyStruct", None, 1, 3),
            si("my_crate::main", "main", Some("() -> ()"), 5, 7),
        ];

        let expanded = vec![
            si("my_crate::MyStruct", "MyStruct", None, 1, 3),
            si("my_crate::main", "main", Some("() -> ()"), 5, 7),
            si(
                "my_crate::<MyStruct as Debug>::fmt",
                "fmt",
                Some("(&self, f: &mut Formatter<'_>) -> Result"),
                10,
                15,
            ),
        ];

        let diff = diff_symbols(&original, &expanded);
        assert_eq!(diff.generated.len(), 1);
        assert_eq!(diff.generated[0], "my_crate::<MyStruct as Debug>::fmt");
        assert!(diff.possibly_modified.is_empty());
        assert!(diff.removed.is_empty());
    }

    #[test]
    fn test_generated_symbol_metadata() {
        let original = vec![];
        let expanded = vec![si(
            "my_crate::generated_fn",
            "generated_fn",
            Some("() -> u32"),
            1,
            3,
        )];

        let diff = diff_symbols(&original, &expanded);
        assert_eq!(diff.generated.len(), 1);
        assert!(diff.removed.is_empty());
    }

    #[test]
    fn test_empty_expansion() {
        let original = vec![si("my_crate::Foo", "Foo", None, 1, 1)];
        let expanded = vec![si("my_crate::Foo", "Foo", None, 1, 1)];

        let diff = diff_symbols(&original, &expanded);
        assert!(diff.is_empty());
        assert_eq!(diff.total_changes(), 0);
    }

    #[test]
    fn test_qualified_name_collision_handling() {
        // Two symbols with the same simple name but different qualified names.
        let original = vec![si("mod_a::Foo", "Foo", None, 1, 1)];
        let expanded = vec![
            si("mod_a::Foo", "Foo", None, 1, 1),
            si("mod_b::Foo", "Foo", None, 5, 5),
        ];

        let diff = diff_symbols(&original, &expanded);
        assert_eq!(diff.generated.len(), 1);
        assert_eq!(diff.generated[0], "mod_b::Foo");
    }

    #[test]
    fn test_non_deterministic_expansion_detection() {
        assert!(is_deterministic("abc123", "abc123"));
        assert!(!is_deterministic("abc123", "def456"));
    }

    #[test]
    fn test_possibly_modified_detection() {
        let original = vec![si("my_crate::foo", "foo", Some("() -> u32"), 1, 3)];
        let expanded = vec![si("my_crate::foo", "foo", Some("(x: i32) -> u32"), 1, 5)];

        let diff = diff_symbols(&original, &expanded);
        assert!(diff.generated.is_empty());
        assert_eq!(diff.possibly_modified.len(), 1);
        assert_eq!(diff.possibly_modified[0], "my_crate::foo");
    }

    #[test]
    fn test_extract_symbols_from_tree() {
        let source = r"
pub struct MyStruct {
    x: u32,
}

impl MyStruct {
    pub fn new() -> Self {
        Self { x: 0 }
    }
}

fn helper() -> u32 {
    42
}
";
        let tree = parse_rust(source);
        let symbols = extract_symbols_from_tree(&tree, source.as_bytes(), "my_crate");

        let names: Vec<&str> = symbols.iter().map(|s| s.qualified_name.as_str()).collect();
        assert!(names.contains(&"my_crate::MyStruct"));
        assert!(names.contains(&"my_crate::MyStruct::new"));
        assert!(names.contains(&"my_crate::helper"));
    }

    #[test]
    fn test_extract_captures_scope_impl_type_and_kind() {
        let source = r"
mod outer {
    pub struct Widget;

    impl Widget {
        pub fn build() -> Self {
            Widget
        }
    }

    pub trait Greeter {
        fn greet(&self) {}
    }
}

const TOP: u32 = 1;
";
        let tree = parse_rust(source);
        let symbols = extract_symbols_from_tree(&tree, source.as_bytes(), "my_crate");

        // Free struct inside a module: scope = [outer(mod)], no impl type.
        let widget = find(&symbols, "my_crate::outer::Widget");
        assert_eq!(widget.kind, GeneratedSymbolKind::Struct);
        assert!(widget.impl_type.is_none());
        assert_eq!(widget.scope_segments.len(), 1);
        assert_eq!(widget.scope_segments[0].name, "outer");
        assert!(widget.scope_segments[0].is_module);

        // Method inside an impl: kind = Method, impl_type = "Widget", the impl
        // pushes NO scope segment (only the module segment remains).
        let build = find(&symbols, "my_crate::outer::Widget::build");
        assert_eq!(build.kind, GeneratedSymbolKind::Method);
        assert_eq!(build.impl_type.as_deref(), Some("Widget"));
        assert_eq!(build.scope_segments.len(), 1);
        assert_eq!(build.scope_segments[0].name, "outer");
        assert!(build.scope_segments[0].is_module);

        // Trait default-body method: no impl block, so kind = Function, and the
        // trait pushes a `is_module: false` scope segment after the module.
        let greet = find(&symbols, "my_crate::outer::Greeter::greet");
        assert_eq!(greet.kind, GeneratedSymbolKind::Function);
        assert!(greet.impl_type.is_none());
        assert_eq!(greet.scope_segments.len(), 2);
        assert_eq!(greet.scope_segments[0].name, "outer");
        assert!(greet.scope_segments[0].is_module);
        assert_eq!(greet.scope_segments[1].name, "Greeter");
        assert!(!greet.scope_segments[1].is_module);

        // Free constant at crate root: no scope, Constant kind.
        let top = find(&symbols, "my_crate::TOP");
        assert_eq!(top.kind, GeneratedSymbolKind::Constant);
        assert!(top.scope_segments.is_empty());
        assert!(top.impl_type.is_none());
    }

    #[test]
    fn test_diff_result_methods() {
        let empty = DiffResult {
            generated: vec![],
            possibly_modified: vec![],
            removed: vec![],
        };
        assert!(empty.is_empty());
        assert_eq!(empty.total_changes(), 0);

        let non_empty = DiffResult {
            generated: vec!["a".to_string()],
            possibly_modified: vec!["b".to_string()],
            removed: vec!["c".to_string(), "d".to_string()],
        };
        assert!(!non_empty.is_empty());
        assert_eq!(non_empty.total_changes(), 4);
    }
}
