//! Macro-generated symbol diffing (4.5f diffing).
//!
//! Compares original and expanded source code to identify symbols that were
//! generated by macro expansion. Uses fully-qualified symbol names (not just
//! simple names) to avoid collisions across modules and impl blocks.
//!
//! # Diffing Strategy
//!
//! 1. Parse both original and expanded source with tree-sitter
//! 2. Extract qualified symbol names from both
//! 3. New symbols = expanded set minus original set
//! 4. Modified symbols = same qualified name but different spans/signatures
//!
//! # Non-deterministic Macros
//!
//! If `cargo expand` produces different output on consecutive runs (checked via
//! SHA-256 of expanded output), the cache entry is marked
//! `confidence: "non_deterministic"` and generated symbols are excluded from
//! the graph.

use std::collections::{HashMap, HashSet};

/// Result of comparing original and expanded symbol sets.
#[derive(Debug, Clone)]
pub struct DiffResult {
    /// Symbols present in expanded but not original — macro-generated.
    pub generated: Vec<String>,
    /// Symbols present in both but with different signatures — possibly modified
    /// by macro expansion.
    pub possibly_modified: Vec<String>,
    /// Symbols present in original but not expanded — removed (rare, usually
    /// indicates a `cfg` gate or conditional compilation difference).
    pub removed: Vec<String>,
}

impl DiffResult {
    /// Returns true if no differences were found.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.generated.is_empty() && self.possibly_modified.is_empty() && self.removed.is_empty()
    }

    /// Total number of differences.
    #[must_use]
    pub fn total_changes(&self) -> usize {
        self.generated.len() + self.possibly_modified.len() + self.removed.len()
    }
}

/// Information about a symbol extracted from source code.
#[derive(Debug, Clone)]
pub struct SymbolInfo {
    /// Fully-qualified name (e.g., `my_crate::MyStruct`, `my_crate::<MyStruct as Debug>::fmt`).
    pub qualified_name: String,
    /// Simple name (e.g., `MyStruct`, `fmt`).
    pub simple_name: String,
    /// Optional signature string for detecting modifications.
    pub signature: Option<String>,
    /// Start line in source (1-indexed).
    pub start_line: u32,
    /// End line in source (1-indexed).
    pub end_line: u32,
}

/// Diff two sets of symbols to find generated, modified, and removed entries.
///
/// Uses fully-qualified names as the key for comparison. Symbols with the
/// same qualified name but different signatures are classified as
/// `possibly_modified`.
///
/// # Arguments
///
/// * `original_symbols` — symbols from the unexpanded source
/// * `expanded_symbols` — symbols from the expanded source
#[must_use]
pub fn diff_symbols(
    original_symbols: &[SymbolInfo],
    expanded_symbols: &[SymbolInfo],
) -> DiffResult {
    let original_by_name: HashMap<&str, &SymbolInfo> = original_symbols
        .iter()
        .map(|s| (s.qualified_name.as_str(), s))
        .collect();

    let expanded_by_name: HashMap<&str, &SymbolInfo> = expanded_symbols
        .iter()
        .map(|s| (s.qualified_name.as_str(), s))
        .collect();

    let original_names: HashSet<&str> = original_by_name.keys().copied().collect();
    let expanded_names: HashSet<&str> = expanded_by_name.keys().copied().collect();

    // Generated = in expanded but not in original.
    let generated: Vec<String> = expanded_names
        .difference(&original_names)
        .map(|name| (*name).to_string())
        .collect();

    // Removed = in original but not in expanded.
    let removed: Vec<String> = original_names
        .difference(&expanded_names)
        .map(|name| (*name).to_string())
        .collect();

    // Possibly modified = in both but with different signatures.
    let possibly_modified: Vec<String> = original_names
        .intersection(&expanded_names)
        .filter(|name| {
            let orig = original_by_name[*name];
            let expanded = expanded_by_name[*name];
            orig.signature != expanded.signature
        })
        .map(|name| (*name).to_string())
        .collect();

    DiffResult {
        generated,
        possibly_modified,
        removed,
    }
}

/// Check if two expansion outputs are deterministic by comparing their SHA-256
/// hashes.
///
/// If the hashes differ, the macro expansion is non-deterministic and should
/// be marked with `confidence: "non_deterministic"`.
///
/// # Arguments
///
/// * `hash_a` — SHA-256 hex digest of the first expansion output
/// * `hash_b` — SHA-256 hex digest of the second expansion output
#[must_use]
pub fn is_deterministic(hash_a: &str, hash_b: &str) -> bool {
    hash_a == hash_b
}

/// Extract symbol names from a tree-sitter parse tree.
///
/// Walks the tree and extracts qualified names for all top-level definitions:
/// functions, structs, enums, traits, impl blocks, type aliases, constants,
/// and statics.
///
/// # Arguments
///
/// * `tree` — parsed tree-sitter tree
/// * `content` — source file bytes
/// * `crate_name` — crate name prefix for qualified names
#[must_use]
pub fn extract_symbols_from_tree(
    tree: &tree_sitter::Tree,
    content: &[u8],
    crate_name: &str,
) -> Vec<SymbolInfo> {
    let mut symbols = Vec::new();
    extract_from_node(tree.root_node(), content, crate_name, &mut symbols);
    symbols
}

/// Recursively extract symbols from a tree-sitter node and its children.
fn extract_from_node(
    node: tree_sitter::Node,
    content: &[u8],
    scope_prefix: &str,
    symbols: &mut Vec<SymbolInfo>,
) {
    let kind = node.kind();

    match kind {
        "function_item" | "struct_item" | "enum_item" | "trait_item" | "type_item"
        | "const_item" | "static_item" | "union_item" => {
            if let Some(name_node) = node.child_by_field_name("name")
                && let Ok(name) = name_node.utf8_text(content)
            {
                let qualified = format!("{scope_prefix}::{name}");
                let signature = extract_signature(node, content);
                symbols.push(SymbolInfo {
                    qualified_name: qualified.clone(),
                    simple_name: name.to_string(),
                    signature,
                    start_line: node.start_position().row as u32 + 1,
                    end_line: node.end_position().row as u32 + 1,
                });

                // Recurse into the body for nested items.
                let child_prefix = qualified;
                extract_children(node, content, &child_prefix, symbols);
                return;
            }
        }

        "impl_item" => {
            if let Some(type_node) = node.child_by_field_name("type")
                && let Ok(type_name) = type_node.utf8_text(content)
            {
                // Check for trait impl: `impl Trait for Type`
                let impl_prefix = if let Some(trait_node) = node.child_by_field_name("trait") {
                    if let Ok(trait_name) = trait_node.utf8_text(content) {
                        format!("{scope_prefix}::<{type_name} as {trait_name}>")
                    } else {
                        format!("{scope_prefix}::{type_name}")
                    }
                } else {
                    format!("{scope_prefix}::{type_name}")
                };

                // Extract methods from the impl body.
                if let Some(body) = node.child_by_field_name("body") {
                    extract_children(body, content, &impl_prefix, symbols);
                }
                return;
            }
        }

        "mod_item" => {
            if let Some(name_node) = node.child_by_field_name("name")
                && let Ok(name) = name_node.utf8_text(content)
            {
                let mod_prefix = format!("{scope_prefix}::{name}");
                extract_children(node, content, &mod_prefix, symbols);
                return;
            }
        }

        _ => {}
    }

    // Default: recurse into children.
    extract_children(node, content, scope_prefix, symbols);
}

/// Extract symbols from a node's children.
fn extract_children(
    node: tree_sitter::Node,
    content: &[u8],
    scope_prefix: &str,
    symbols: &mut Vec<SymbolInfo>,
) {
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        extract_from_node(child, content, scope_prefix, symbols);
    }
}

/// Extract a simplified signature from a function or type definition.
fn extract_signature(node: tree_sitter::Node, content: &[u8]) -> Option<String> {
    match node.kind() {
        "function_item" => {
            // Extract parameter list and return type.
            let params = node
                .child_by_field_name("parameters")
                .and_then(|n| n.utf8_text(content).ok())
                .unwrap_or("()");
            let return_type = node
                .child_by_field_name("return_type")
                .and_then(|n| n.utf8_text(content).ok())
                .unwrap_or("");
            Some(format!("{params} {return_type}").trim().to_string())
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tree_sitter::Parser;

    fn parse_rust(source: &str) -> tree_sitter::Tree {
        let mut parser = Parser::new();
        let lang: tree_sitter::Language = tree_sitter_rust::LANGUAGE.into();
        parser.set_language(&lang).unwrap();
        parser.parse(source.as_bytes(), None).unwrap()
    }

    #[test]
    fn test_symbol_diffing() {
        let original = vec![
            SymbolInfo {
                qualified_name: "my_crate::MyStruct".to_string(),
                simple_name: "MyStruct".to_string(),
                signature: None,
                start_line: 1,
                end_line: 3,
            },
            SymbolInfo {
                qualified_name: "my_crate::main".to_string(),
                simple_name: "main".to_string(),
                signature: Some("() -> ()".to_string()),
                start_line: 5,
                end_line: 7,
            },
        ];

        let expanded = vec![
            SymbolInfo {
                qualified_name: "my_crate::MyStruct".to_string(),
                simple_name: "MyStruct".to_string(),
                signature: None,
                start_line: 1,
                end_line: 3,
            },
            SymbolInfo {
                qualified_name: "my_crate::main".to_string(),
                simple_name: "main".to_string(),
                signature: Some("() -> ()".to_string()),
                start_line: 5,
                end_line: 7,
            },
            SymbolInfo {
                qualified_name: "my_crate::<MyStruct as Debug>::fmt".to_string(),
                simple_name: "fmt".to_string(),
                signature: Some("(&self, f: &mut Formatter<'_>) -> Result".to_string()),
                start_line: 10,
                end_line: 15,
            },
        ];

        let diff = diff_symbols(&original, &expanded);
        assert_eq!(diff.generated.len(), 1);
        assert_eq!(diff.generated[0], "my_crate::<MyStruct as Debug>::fmt");
        assert!(diff.possibly_modified.is_empty());
        assert!(diff.removed.is_empty());
    }

    #[test]
    fn test_generated_symbol_metadata() {
        let original = vec![];
        let expanded = vec![SymbolInfo {
            qualified_name: "my_crate::generated_fn".to_string(),
            simple_name: "generated_fn".to_string(),
            signature: Some("() -> u32".to_string()),
            start_line: 1,
            end_line: 3,
        }];

        let diff = diff_symbols(&original, &expanded);
        assert_eq!(diff.generated.len(), 1);
        assert!(diff.removed.is_empty());
    }

    #[test]
    fn test_empty_expansion() {
        let original = vec![SymbolInfo {
            qualified_name: "my_crate::Foo".to_string(),
            simple_name: "Foo".to_string(),
            signature: None,
            start_line: 1,
            end_line: 1,
        }];
        let expanded = vec![SymbolInfo {
            qualified_name: "my_crate::Foo".to_string(),
            simple_name: "Foo".to_string(),
            signature: None,
            start_line: 1,
            end_line: 1,
        }];

        let diff = diff_symbols(&original, &expanded);
        assert!(diff.is_empty());
        assert_eq!(diff.total_changes(), 0);
    }

    #[test]
    fn test_qualified_name_collision_handling() {
        // Two symbols with the same simple name but different qualified names.
        let original = vec![SymbolInfo {
            qualified_name: "mod_a::Foo".to_string(),
            simple_name: "Foo".to_string(),
            signature: None,
            start_line: 1,
            end_line: 1,
        }];
        let expanded = vec![
            SymbolInfo {
                qualified_name: "mod_a::Foo".to_string(),
                simple_name: "Foo".to_string(),
                signature: None,
                start_line: 1,
                end_line: 1,
            },
            SymbolInfo {
                qualified_name: "mod_b::Foo".to_string(),
                simple_name: "Foo".to_string(),
                signature: None,
                start_line: 5,
                end_line: 5,
            },
        ];

        let diff = diff_symbols(&original, &expanded);
        assert_eq!(diff.generated.len(), 1);
        assert_eq!(diff.generated[0], "mod_b::Foo");
    }

    #[test]
    fn test_non_deterministic_expansion_detection() {
        assert!(is_deterministic("abc123", "abc123"));
        assert!(!is_deterministic("abc123", "def456"));
    }

    #[test]
    fn test_possibly_modified_detection() {
        let original = vec![SymbolInfo {
            qualified_name: "my_crate::foo".to_string(),
            simple_name: "foo".to_string(),
            signature: Some("() -> u32".to_string()),
            start_line: 1,
            end_line: 3,
        }];
        let expanded = vec![SymbolInfo {
            qualified_name: "my_crate::foo".to_string(),
            simple_name: "foo".to_string(),
            signature: Some("(x: i32) -> u32".to_string()),
            start_line: 1,
            end_line: 5,
        }];

        let diff = diff_symbols(&original, &expanded);
        assert!(diff.generated.is_empty());
        assert_eq!(diff.possibly_modified.len(), 1);
        assert_eq!(diff.possibly_modified[0], "my_crate::foo");
    }

    #[test]
    fn test_extract_symbols_from_tree() {
        let source = r#"
pub struct MyStruct {
    x: u32,
}

impl MyStruct {
    pub fn new() -> Self {
        Self { x: 0 }
    }
}

fn helper() -> u32 {
    42
}
"#;
        let tree = parse_rust(source);
        let symbols = extract_symbols_from_tree(&tree, source.as_bytes(), "my_crate");

        let names: Vec<&str> = symbols.iter().map(|s| s.qualified_name.as_str()).collect();
        assert!(names.contains(&"my_crate::MyStruct"));
        assert!(names.contains(&"my_crate::MyStruct::new"));
        assert!(names.contains(&"my_crate::helper"));
    }

    #[test]
    fn test_diff_result_methods() {
        let empty = DiffResult {
            generated: vec![],
            possibly_modified: vec![],
            removed: vec![],
        };
        assert!(empty.is_empty());
        assert_eq!(empty.total_changes(), 0);

        let non_empty = DiffResult {
            generated: vec!["a".to_string()],
            possibly_modified: vec!["b".to_string()],
            removed: vec!["c".to_string(), "d".to_string()],
        };
        assert!(!non_empty.is_empty());
        assert_eq!(non_empty.total_changes(), 4);
    }
}
